### ISSUE TITLE
New Maropost API Update

### ISSUE THREAD

**Issue by chasebros** [infusedmj/maropost-php-sdk#1]
With Maroposts update this url static $url_api  = "http://app.maropost.com/accounts/{ENTER MAROPOST ACCT ID}/"; needs to be updated to static $url_api  = "http://api.maropost.com/accounts/{ENTER MAROPOST ACCT ID}/";

**Comment by infusedmj** [comment]
This has been fixed. Thank you for taking time to report the issue.
